# Generated by Django 4.1.7 on 2023-03-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentIteration', models.IntegerField()),
                ('maxIteration', models.IntegerField()),
                ('startValue', models.FloatField()),
            ],
        ),
    ]
