# Generated by Django 4.1.7 on 2023-03-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_iteration_converged_iteration_polynomial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
