# Generated by Django 4.1.7 on 2023-03-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_iteration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='convergeValue',
            field=models.FloatField(default=0.0),
        ),
    ]
