# Generated by Django 4.1.7 on 2023-03-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_iteration_convergevalue_iterationstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='maxIteration',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
