# Generated by Django 4.1.7 on 2023-03-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_iteration_maxiteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='maxIteration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='startValue',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
