# Generated by Django 4.1.7 on 2023-03-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_iteration_allmatrices"),
        ("main", "0007_alter_iteration_maxiteration_and_more"),
    ]

    operations = []
