# Generated by Django 4.1.7 on 2023-03-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_merge_20230323_1841"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iteration",
            name="allMatrices",
        ),
    ]
